### ISSUE TITLE
Merged posts don't appear to be publishing

### ISSUE THREAD

**Issue by ggotti** [ippontech/blog-usa#114]
The automated publishing option doesn't appear to be working; the merged posts are not appearing on the website. My understanding was that the process was supposed to be automated once merged in.

**Comment by Throckmortra** [comment]
When merged, your post should appear unpublished in the ghost backend. I will make sure it gets published. I'm just trying to space out the blog posts

**Comment by ggotti** [comment]
Thanks @Throckmortra :)
